# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buyer.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62uyer.proto\"\x07\n\x05Void1\"\x1e\n\x0bNotifybuyer\x12\x0f\n\x07message\x18\x01 \x01(\t23\n\x05\x42uyer\x12*\n\x12\x42uyer_Notification\x12\x0c.Notifybuyer\x1a\x06.Void1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buyer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOID1']._serialized_start=15
  _globals['_VOID1']._serialized_end=22
  _globals['_NOTIFYBUYER']._serialized_start=24
  _globals['_NOTIFYBUYER']._serialized_end=54
  _globals['_BUYER']._serialized_start=56
  _globals['_BUYER']._serialized_end=107
# @@protoc_insertion_point(module_scope)
