# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: seller.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cseller.proto\"\x06\n\x04Void\"&\n\x13NotifyClientRequest\x12\x0f\n\x07message\x18\x01 \x01(\t2<\n\x06Seller\x12\x32\n\x13Seller_Notification\x12\x14.NotifyClientRequest\x1a\x05.Voidb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'seller_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOID']._serialized_start=16
  _globals['_VOID']._serialized_end=22
  _globals['_NOTIFYCLIENTREQUEST']._serialized_start=24
  _globals['_NOTIFYCLIENTREQUEST']._serialized_end=62
  _globals['_SELLER']._serialized_start=64
  _globals['_SELLER']._serialized_end=124
# @@protoc_insertion_point(module_scope)
